% %% create leg class
% 
% classdef Leg
%        enumeration
%       Monday, Tuesday, Wednesday, Thursday, Friday
%        
% %       properties
% %       link1 = struct('name', [], ...
% %                      'length', [], ...
% %                      'mass', [], ...
% %                      'inertia', []);
% %       link2 = struct('name', [], ...
% %                      'length', [], ...
% %                      'mass', [], ...
% %                      'inertia', []);
% %       link3 = struct('name', [], ...
% %                      'length', [], ...
% %                      'mass', [], ...
% %                      'inertia', []);
% %       joint1 = struct('name', [], ...
% %                       'q', [], ...
% %                       'qdot', [], ...
% %                       'qdotdot', [], ...
% %                       'torque', []);
% %       joint2 = struct('name', [], ...
% %                       'q', [], ...
% %                       'qdot', [], ...
% %                       'qdotdot', [], ...
% %                       'torque', [], ...
% %                       'pos', []);
% %       joint3 = struct('name', [], ...
% %                       'q', [], ...
% %                       'qdot', [], ...
% %                       'qdotdot', [], ...
% %                       'torque', [], ...
% %                       'pos', [])
% %       joint4 = struct('name', [], ...
% %                       'q', [], ...
% %                       'qdot', [], ...
% %                       'qdotdot', [], ...
% %                       'torque', [], ...
% %                       'pos', []);
% %       density
%       end
% end


classdef Leg
   enumeration
      Monday, Tuesday, Wednesday, Thursday, Friday
   end
end
