% Example calling function from saved results data: tabulateResults(results.ANYmal, 'flyingTrot')
function [] = tabulateResults(data)

    robotClass             = data.basicProperties.classSelection;
    EEnames                = data.basicProperties.EEnames;
    base                   = data.base; % base motion for each leg during its cycle
    base.fullTrajectory    = data.fullTrajectory.base;
    legCount               = data.basicProperties.legCount;
    linkCount              = data.basicProperties.linkCount;
    linkNames              = data.basicProperties.linkNames';
    jointActuationMethod   = data.basicProperties.jointActuationType;
    transmissionMethod     = data.basicProperties.transmissionMethod;
    optimizationProperties = data.optimizationProperties;
    allowableExtension     = data.optimizationProperties.allowableExtension;
    task                   = data.basicProperties.task;
    linkNames              = strjoin(linkNames);
    jointNames             = data.basicProperties.jointNames(1,:);
    actuatorSelection      = data.actuatorProperties.actuatorSelection.(data.basicProperties.jointNames(1,:));
    actuationMethod        = jointActuationMethod.HAA;
    transmission           = transmissionMethod.HAA;
    robotMass              = data.robotProperties.mass.total;
     
    %% Basic properties table
    for i = 2:linkCount+1 % Fill out the rest of the list programatically
        jointNames = [jointNames, ' ', data.basicProperties.jointNames(i,:)];
        actuatorSelection = [actuatorSelection, ' ', data.actuatorProperties.actuatorSelection.(data.basicProperties.jointNames(i,:))];  
        actuationMethod = [actuationMethod, ' ', jointActuationMethod.(data.basicProperties.jointNames(i,:))];
        transmission = [transmission, ' ', transmissionMethod.(data.basicProperties.jointNames(i,:))];
    end
    
    rowNames = {'Robot class',...
                'Task', ...
                'Leg quantity', ...
                'Link names', ...
                'Joint names', ...
                'Actuator selection', ...
                'Joint actuation method', ...
                'Transmission method'};

    Basic_Properties = [string(robotClass); ...
                        string(task); ...
                        legCount; ...
                        string(linkNames); ...
                        string(jointNames); ...
                        string(actuatorSelection); ...
                        string(actuationMethod); ...                        
                        string(transmission)];
                    
   T = table(Basic_Properties, 'RowNames', rowNames)
   
    %% Optimization settings table
    % Go through the penalty terms and add them to the list of imposed
    % terms if the value is 1, otherwise do not add them to the list.

           
    for i = 1:legCount
        EEselection = EEnames(i,:);
        
            optimizedLegs = [];
            rowNames = {'Optimized legs',...
                        'Number of generations', ...
                        'Population size', ...
                        'Allowable leg extension/Total possible leg extension'};
        
        if data.basicProperties.optimizedLegs.(EEselection) 
            optimizedLegs = [optimizedLegs, ' ', EEselection];
            generationCount = data.optimizationProperties.gaSettings.(EEselection).generations;
            populationSize = floor(data.optimizationProperties.gaSettings.(EEselection).funccount/(1+generationCount));

    Optimization_Properties = [string(optimizedLegs); ...
                               string(generationCount); ...
                               string(populationSize); ... 
                               string(allowableExtension)];
                                                   
    softConstraintCount = 0;                       
    if optimizationProperties.imposeJointLimits.maxTorque
        softConstraintCount = softConstraintCount + 1;
        s1 = num2str(softConstraintCount);
        s = strcat('Constraint',s1);
        rowNames(end+1) = {s};
        Optimization_Properties(end+1) = {'Impose max actuator torque limit'};
    end
    
    if optimizationProperties.imposeJointLimits.maxqdot
        softConstraintCount = softConstraintCount + 1;
        s1 = num2str(softConstraintCount);
        s = strcat('Constraint',s1);
        rowNames(end+1) = {s};
        Optimization_Properties(end+1) = {'Impose max actuator speed limit'};        
    end

    if optimizationProperties.imposeJointLimits.maxPower
        softConstraintCount = softConstraintCount + 1;
        s1 = num2str(softConstraintCount);
        s = strcat('Constraint',s1);
        rowNames(end+1) = {s};     
        Optimization_Properties(end+1) = {'Impose max actuator power limit'};        
    end    
    
    penaltyMessage = {'Penalize total swing torque'; ...
                      'Penalize total stance torque'; ...
                      'Penalize total torque'; ...
                      'Penalize total HFE torque'; ...
                      'Penalize total KFE torque'; ...
                      'Penalize HFE swing torque'; ...
                      'Penalize total active torque'; ...
                      'Penalize total active torque in stance'; ...
                      'Penalize total joint velocity'; ...
                      'Penalize total joint power'; ...
                      'Penalize total mechanical energy'; ...
                      'Penalize total electrical energy'; ...
                      'Penalize inverse of efficiency'; ...
                      'Penalize max torque'; ...
                      'Penalize max joint velocity'; ...
                      'Penalize max power'; ...
                      'Penalize antagonistic power'; ...
                      'Penalize mechanical cost of transport'; ...
                      'Penalize leg extension beyond allowable limit'};
                      
    penaltyFields = fieldnames(optimizationProperties.penaltyWeight);
    costTermCount = 0;
    for i = 1:length(penaltyFields)      
        if optimizationProperties.penaltyWeight.(penaltyFields{i})
            costTermCount = costTermCount +1;
            c1 = num2str(costTermCount);
            c = strcat('Cost',c1);
            rowNames(end+1) = {c};
            Optimization_Properties(end+1) = penaltyMessage{i};         
        end  
    end
     
    T = table(Optimization_Properties, 'RowNames', rowNames)
      end
end

    %% Nominal results of simulation
   for i = 1:legCount
       EEselection = EEnames(i,:);
       
       rowNames = {'Leg'
                   'Link lengths [m]'; ...
                   'Link mass [kg]'; ...
                   'Total link mass [kg]'; ...
                   'Change in total link mass [kg]'; ...
                   'Change in link mass/robot total nominal mass [%]'; ...
                   'Maximum joint torque [Nm]'; ...
                   'Maximum joint speed [rad/s]'; ...
                   'Maximum mechanical power [W]'; ...
                   'Mechanical energy consumption [J/cycle]'; ...
                   'Cost of transport'; ...
                   'Power quality'; ...
                   'Joint angle range [rad]'; ...
                   'Transmission gear ratio'
                   'Joint spring constants'};

      Nominal_Leg =  [string(EEselection); ...
                      strjoin(string(data.(EEselection).linkLengths(1,:))); ...
                      strjoin(string(data.(EEselection).linkMass(1,:))); ...
                      strjoin(string(data.(EEselection).totalLinkMass)); ...
                      'NA';
                      'NA';
                      strjoin(string(data.metaParameters.jointTorqueMax.(EEselection)(1,:))); ...
                      strjoin(string(data.metaParameters.qdotMax.(EEselection)(1,:))); ...
                      strjoin(string(data.metaParameters.jointPowerMax.(EEselection)(1,:))); ...
                      strjoin(string(data.metaParameters.mechEnergyPerCycle.(EEselection)(1,:))); ... 
                      data.metaParameters.CoT.(EEselection); ...
                      strjoin(string(data.metaParameters.powerQuality.(EEselection)(1,:))); ...
                      strjoin(string(data.metaParameters.deltaqMax.(EEselection)(1,:))); ...
                      strjoin(string(data.(EEselection).transmissionGearRatio))
                      strjoin(string(data.(EEselection).kSpringJoint(1,1:linkCount+1)))];
   
     if data.basicProperties.optimizedLegs.(EEselection) 
        Optimized_Leg = [string(EEselection); ...
                         strjoin(string(data.(EEselection).linkLengthsOpt(1,:))); ...
                         strjoin(string(data.(EEselection).linkMassOpt(1,:))); ...
                         strjoin(string(data.(EEselection).totalLinkMassOpt)); ...
                         strjoin(string(data.(EEselection).totalLinkMassOpt - data.(EEselection).totalLinkMass)); ...
                         strjoin(string(100*(data.(EEselection).totalLinkMassOpt - data.(EEselection).totalLinkMass)/robotMass)); ...
                         strjoin(string(data.metaParameters.jointTorqueMaxOpt.(EEselection)(1,:))); ...
                         strjoin(string(data.metaParameters.qdotMaxOpt.(EEselection)(1,:))); ...
                         strjoin(string(data.metaParameters.jointPowerMaxOpt.(EEselection)(1,:))); ...
                         strjoin(string(data.metaParameters.mechEnergyPerCycleOpt.(EEselection)(1,:))); ... 
                         data.metaParameters.CoTOpt.(EEselection); ...
                         strjoin(string(data.metaParameters.powerQualityOpt.(EEselection)(1,:))); ...
                         strjoin(string(data.metaParameters.deltaqMaxOpt.(EEselection)(1,:))); ...
                         strjoin(string(data.(EEselection).transmissionGearRatioOpt))
                         strjoin(string(data.(EEselection).kSpringJointOpt(1,1:linkCount+1)))];   
                  
        T = table(Nominal_Leg, Optimized_Leg, 'RowNames', rowNames)
     else 
        T = table(Nominal_Leg, 'RowNames', rowNames)
     end          
end